### PR TITLE
Integration tests for polarion support

### PR DESCRIPTION
**Pull request by jscotka**

### CODE REVIEW

**Comment by psss** [comment]
From the failing tests it seems the `plans/create_pylero_cfg.sh` file has not been included in the commit.

**Comment by jscotka** [comment]
> From the failing tests it seems the `plans/create_pylero_cfg.sh` file has not been included in the commit.

Ah thanks, copied locally, so that I've verifoied that tests works well, but forgot to git add :-)
But currently I'm testing rpm installed TMT version, not sure how it works, if we add remote plan into `tmt` if there will stay rpm version or locally installed tmt will win @psss ?

**Comment by psss** [comment]
> But currently I'm testing rpm installed TMT version, not sure how it works, if we add remote plan into `tmt` if there will stay rpm version or locally installed tmt will win @psss ?

When running here the latest released `tmt` packages will be tested, when running the remote plan from the `tmt` repo, the fresh stuff from the git repo will be verified. I think this should be working relatively fine if there not too many pull requests open in the `tests` repo.

**Comment by psss** [comment]
Hm, tests passed but the test output seems to be empty. Any idea what might be wrong?

**Comment by jscotka** [comment]
> Hm, tests passed but the test output seems to be empty. Any idea what might be wrong?

Forgot to add `.fmf/version` file into test data

**Review by psss — APPROVED** [review]
Thanks much for adding the coverage. Looks good. The binary data contains some internal links but I've checked that those have been published many times before us so that's nothing new. Added just a few adjustments in 5dda207. Please, have a look if everything is ok.

**Pull request merged**
